version: '3.2'
services:
  db:
    image: "mysql:5.7"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 43306:3306
    volumes:
      - type: bind
        source: ./docker/mysql/init
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: /tmp/docker/tmpdata
        target: /tmp/tmpdata

